### ISSUE TITLE
Revision history

### ISSUE THREAD

**Issue by rhattersley** [cf-metadata/convert#1]
re: "Preface" and "Appendix G Revision History"

Assuming this concept becomes obsolete with the proposed workflow...

 - [ ] The description in the preface is incompatible with the removal of highlighting.
 - [ ] The wording in the preface needs updating but the appendix should probably stay.

**Comment by rhattersley** [comment]
@ocefpaf ... how about we start collating/fixing issues in this repo?

**Comment by ocefpaf** [comment]
Good idea!  Let me see if I can find a few to start collating (and hopefully fix some along the way).
