### ISSUE TITLE
Notes while reading

### ISSUE THREAD

**Issue by ocefpaf** [cf-metadata/convert#13]
@rhattersley These are not a real issues.  Just some notes I am taking while reading the original version (OC) and the converted version (CV) version side-by-side.
- No `List of Tables` in the CV
- No `List of Examples` CV
- No `Abstract` CV
- Some of the appendices (like D) are itemized in the CV TOC but not in the OV
- The appendices items are numbered in the OV (e.g.: H.2.1, H.2.2 etc)
- Internal links start with "Section, ..." in the OV
- [Issue #4] ~~OV display a small `Table of Contents` in the beginning of each chapter~~
- [Issue #14] ~~The examples are not number based the section that they are shown the CV.  For example: the first one, on section 3, is numbered 1 instead of 3.1~~
- [Issues #11 and #12] ~~Sometimes the title and the description of the examples "leak" inside the example box in the CV.  See the first example where we have `standard_name` and `The description...` inside the box.  That does happen in example 2.~~

Overall the document looks much nicer than the original.  It almost make me want to read the CF-conventions in full :grin:

**Comment by rhattersley** [comment]
Thanks @ocefpaf :smile:

To make them easier to track I'll split some of your comments out into separate issues.

> Overall the document looks much nicer than the original. It almost make me want to read the CF-conventions in full :grin:

High praise indeed! :wink:

**Comment by ocefpaf** [comment]
Just now I realized you already had issues opened for most of them.  When I finish up reading I will close this one and leave just the split issues to avoid noise.
